Add download functionality directly from Azure via SAS token URL
deepan10/backstage-plugins pull request #4
Opened 2024-04-07 16:25 UTC by QuadmanSWE

Added button in front end to download with sas token.

My original requirement is for another front end plugin that want to levarage direct blob storage download of known URIs for acc/container/prefix/blob.

I added functionality to backend (when supported by the type of credentials for the respective storage accounts) to generate a 15 minute SAS token for a direct download by the client without authentication.

I am thinking that this could be opt in via configuration for one or more download types per storage account instead of always being available for each account that supports either. We could also make the life time of the SAS token configurable there.

I changed the tooltip for the existing download button to reflect that its via the backend where as the other is via SAS token.

2024-04-07 16:32 UTC, QuadmanSWE commented
fixes #3

2024-04-15 15:07 UTC, QuadmanSWE commented
@deepan10 when would you be available to do a code review together with me?

2024-04-18 07:42 UTC, deepan10 requested changes

2024-04-18 07:42 UTC, deepan10 commented on plugins/azure-storage/src/components/AzureStoragePage/AzureStorageContent.tsx
> +    azureStorageApi.downloadBlob(
I hope this is going to the backend download only. 
```suggestion
    azureStorageApi.downloadBlobDirectly(
```

2024-04-18 07:42 UTC, deepan10 commented on plugins/azure-storage/src/api/AzureStorageClient.ts
> +    const downloadLink: string = await this.getDownloadLink(
```suggestion
   export type DownloadLink = (
      { url: string }
    );
    ....
    const downloadLink: DownloadLink = await this.getDownloadLink(
```

2024-04-18 07:42 UTC, deepan10 commented on plugins/azure-storage/src/api/AzureStorageClient.ts
> +    await fetch(downloadLink)
```suggestion
    await fetch(downloadLink.url)
```

2024-04-18 07:42 UTC, deepan10 commented on plugins/azure-storage/src/api/AzureStorageClient.ts
> +      .then(response => response.json())
```suggestion
      .then(response => response.blob())
```

2024-04-18 07:42 UTC, deepan10 commented
Hello @QuadmanSWE 
Sorry I was sick and back now. I just did the review. Please have a look at it.

2024-04-25 10:49 UTC, QuadmanSWE commented
Thanks for the review. So there is quite a lot that didn't work out even with your adjustments but I got it to work as I wanted in our backstage using a fork of your plugin.

I will close this and redo it including docs on what needs to be done on the storage account in azure to make it work flawlessly, (CORS settings)

2024-04-25 10:49 UTC, closed without merging